security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        users:
            entity:
                class: App\Entity\User
                property: pseudo
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        register:
            pattern: ^/myapi/register$
            anonymous: true

        api_login:
            pattern: ^/myapi/authenticate
            anonymous: false
            stateless: true
            json_login:
                username_path: user
                password_path: password
                check_path: api_login

        api:
            pattern: ^/myapi
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Security\ApiAuthenticator

    access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
